import { Room } from "./types";

export const rooms51to75: Room[] = [
    { id: "room-51", title: "The Spy Headquarters", difficulty: "Hard", duration: "40 mins", description: "Deep inside enemy spy headquarters. Extract the intel without being detected.", theme: "Noir", imagePrompt: "Spy headquarters, monitors, filing cabinets, secret passages", isPremium: true, puzzles: [{ id: "p51", question: "Spy code: A=Z, B=Y, C=X. Encode 'SPY'.", type: "code", answer: "HKB", hints: ["S is 19th letter, Z minus 18", "Reverse alphabet"], solution_explanation: "S=H, P=K, Y=B using reverse alphabet" }] },
    { id: "room-52", title: "The Abandoned Hospital", difficulty: "Hard", duration: "45 mins", description: "An old psychiatric ward. Patient files hold the key to your escape.", theme: "Horror", imagePrompt: "Abandoned hospital corridor, wheelchairs, flickering lights", isPremium: true, puzzles: [{ id: "p52", question: "Ward numbers: A=100, B=200, C=300. Patient in ward B+C?", type: "code", answer: "500", hints: ["Add the values", "200 + 300"], solution_explanation: "200 + 300 = 500" }] },
    { id: "room-53", title: "The Bakery", difficulty: "Easy", duration: "15 mins", description: "A charming French bakery with a recipe puzzle.", theme: "Cozy", imagePrompt: "French bakery interior, fresh bread, pastries, warm lighting", isPremium: false, puzzles: [{ id: "p53", question: "Recipe calls for double the flour. If original is 2 cups, how much now?", type: "code", answer: "4", hints: ["Double means multiply by 2"], solution_explanation: "2 × 2 = 4 cups" }] },
    { id: "room-54", title: "Atlantis Rising", difficulty: "Expert", duration: "55 mins", description: "The legendary underwater city emerges. Decode the ancient water gates.", theme: "Mythic", imagePrompt: "Atlantis underwater ruins, coral, ancient technology, bioluminescence", isPremium: true, puzzles: [{ id: "p54", question: "Poseidon's trident has 3 prongs. If each prong controls 7 seas, total seas?", type: "code", answer: "21", hints: ["Simple multiplication", "3 × 7"], solution_explanation: "3 × 7 = 21 seas" }] },
    { id: "room-55", title: "The Wild West Saloon", difficulty: "Medium", duration: "25 mins", description: "High noon in a dusty saloon. The sheriff left clues.", theme: "Historical", imagePrompt: "Western saloon, swinging doors, poker table, wanted posters", isPremium: true, puzzles: [{ id: "p55", question: "Wanted poster bounty: $500 dead, $1000 alive. Difference?", type: "code", answer: "500", hints: ["Subtract dead from alive", "1000 - 500"], solution_explanation: "$1000 - $500 = $500" }] },
    { id: "room-56", title: "The Time Machine", difficulty: "Expert", duration: "60 mins", description: "Inside H.G. Wells' time machine. Set the correct era to escape.", theme: "Time Travel", imagePrompt: "Steampunk time machine interior, dials, date displays, sparks", isPremium: true, puzzles: [{ id: "p56", question: "The machine shows year palindromes. What comes after 2002?", type: "code", answer: "2112", hints: ["Reads same forward and backward", "Next after 2002"], solution_explanation: "2112 is the next palindrome after 2002" }] },
    { id: "room-57", title: "The Toy Factory", difficulty: "Easy", duration: "20 mins", description: "Santa's workshop has a puzzle malfunction.", theme: "Fantasy", imagePrompt: "Toy factory, assembly line, colorful toys, elves", isPremium: false, puzzles: [{ id: "p57", question: "Elves make 10 toys/hour. How many in 3 hours?", type: "code", answer: "30", hints: ["Multiply", "10 × 3"], solution_explanation: "10 × 3 = 30 toys" }] },
    { id: "room-58", title: "The Crypt", difficulty: "Hard", duration: "40 mins", description: "Ancient catacombs beneath a cathedral. The dead hold secrets.", theme: "Horror", imagePrompt: "Stone crypt, coffins, candlelight, skulls, ancient inscriptions", isPremium: true, puzzles: [{ id: "p58", question: "Tombstone dates: Birth 1750, Death 1800. Age at death?", type: "code", answer: "50", hints: ["Subtract birth from death"], solution_explanation: "1800 - 1750 = 50 years" }] },
    { id: "room-59", title: "The Zen Garden", difficulty: "Medium", duration: "25 mins", description: "A peaceful Japanese garden concealing a samurai's secret.", theme: "Ancient", imagePrompt: "Japanese zen garden, rock patterns, bonsai, temple gate", isPremium: true, puzzles: [{ id: "p59", question: "In Japanese numerology: 四 (shi) means 4. What is 四+四?", type: "code", answer: "8", hints: ["4 + 4"], solution_explanation: "4 + 4 = 8" }] },
    { id: "room-60", title: "Moon Base Omega", difficulty: "Hard", duration: "45 mins", description: "A lunar colony in crisis. Oxygen reserves are critical.", theme: "Space", imagePrompt: "Moon base interior, airlocks, Earth visible, life support systems", isPremium: true, puzzles: [{ id: "p60", question: "O2 at 25%, need 100%. How much % to add?", type: "code", answer: "75", hints: ["100 - 25"], solution_explanation: "100 - 25 = 75%" }] },
    { id: "room-61", title: "The Dollhouse", difficulty: "Medium", duration: "30 mins", description: "A life-sized dollhouse. Everything is eerily perfect.", theme: "Horror", imagePrompt: "Giant dollhouse interior, porcelain dolls, pink curtains, uncanny", isPremium: true, puzzles: [{ id: "p61", question: "Doll collection: 5 porcelain, 3 cloth, 2 wooden. Total dolls?", type: "code", answer: "10", hints: ["Add all"], solution_explanation: "5 + 3 + 2 = 10" }] },
    { id: "room-62", title: "The Windmill", difficulty: "Easy", duration: "20 mins", description: "An old Dutch windmill with grinding gears and grain puzzles.", theme: "Cozy", imagePrompt: "Windmill interior, wooden gears, grain sacks, flour dust", isPremium: false, puzzles: [{ id: "p62", question: "Windmill has 4 blades. After 3 quarter turns, how many blades face up?", type: "code", answer: "1", hints: ["Quarter turn = 90°", "Same as 3/4 turn"], solution_explanation: "After 270°, 1 blade faces up" }] },
    { id: "room-63", title: "The Stock Exchange", difficulty: "Hard", duration: "40 mins", description: "Wall Street after hours. Financial codes unlock the vault.", theme: "Noir", imagePrompt: "Stock exchange floor, ticker tape, screens, vault door", isPremium: true, puzzles: [{ id: "p63", question: "Stock rose 10%, then fell 10%. Starting at $100, final price?", type: "code", answer: "99", hints: ["Not $100", "$110 then 10% of that down"], solution_explanation: "$100 × 1.1 = $110, then $110 × 0.9 = $99" }] },
    { id: "room-64", title: "The Comic Book Store", difficulty: "Easy", duration: "15 mins", description: "A geeky paradise with superhero puzzles.", theme: "Fantasy", imagePrompt: "Comic store, shelves of comics, superhero posters, collectibles", isPremium: false, puzzles: [{ id: "p64", question: "Superman's home planet?", type: "choice", options: ["Krypton", "Mars", "Asgard", "Vulcan"], answer: "Krypton", hints: ["Starts with K"], solution_explanation: "Superman is from Krypton" }] },
    { id: "room-65", title: "The Brewery", difficulty: "Medium", duration: "30 mins", description: "A craft brewery with recipe codes.", theme: "Industrial", imagePrompt: "Craft brewery, copper vats, hop flowers, barrels", isPremium: true, puzzles: [{ id: "p65", question: "Recipe: 2 parts hops, 3 parts malt. Ratio simplified?", type: "code", answer: "2:3", hints: ["Already simplified"], solution_explanation: "2:3 is the simplified ratio" }] },
    { id: "room-66", title: "The Radio Tower", difficulty: "Hard", duration: "45 mins", description: "An abandoned radio station broadcasting cryptic signals.", theme: "Mystery", imagePrompt: "Radio tower control room, vintage equipment, frequency dials", isPremium: true, puzzles: [{ id: "p66", question: "Frequency 88.1 + 12.9 = ?", type: "code", answer: "101", hints: ["Simple addition"], solution_explanation: "88.1 + 12.9 = 101.0 FM" }] },
    { id: "room-67", title: "The Ice Cave", difficulty: "Medium", duration: "30 mins", description: "A frozen cavern with crystal formations.", theme: "Mystery", imagePrompt: "Ice cave, frozen stalactites, blue glow, frost crystals", isPremium: true, puzzles: [{ id: "p67", question: "Water freezes at? (Celsius)", type: "code", answer: "0", hints: ["Freezing point of water"], solution_explanation: "Water freezes at 0°C" }] },
    { id: "room-68", title: "The Jazz Club", difficulty: "Easy", duration: "20 mins", description: "A smoky 1920s jazz club with musical clues.", theme: "Noir", imagePrompt: "Jazz club, saxophone, velvet curtains, spotlight", isPremium: false, puzzles: [{ id: "p68", question: "A jazz quartet has how many musicians?", type: "code", answer: "4", hints: ["Quad = 4"], solution_explanation: "Quartet means 4" }] },
    { id: "room-69", title: "The Planetarium", difficulty: "Medium", duration: "35 mins", description: "Stars project secrets on the dome ceiling.", theme: "Astronomy", imagePrompt: "Planetarium dome, star projector, constellation patterns", isPremium: true, puzzles: [{ id: "p69", question: "Orion has 3 stars in his belt. How many in Big Dipper?", type: "code", answer: "7", hints: ["Count the famous constellation"], solution_explanation: "Big Dipper has 7 stars" }] },
    { id: "room-70", title: "The Treehouse", difficulty: "Easy", duration: "15 mins", description: "A magical childhood treehouse high in an ancient oak.", theme: "Cozy", imagePrompt: "Treehouse interior, rope ladders, fairy lights, wooden planks", isPremium: false, puzzles: [{ id: "p70", question: "Ladder rungs: 1st to 10th floor. Rungs between them?", type: "code", answer: "9", hints: ["10 - 1 = 9 gaps"], solution_explanation: "9 intervals between 10 floors" }] },
    { id: "room-71", title: "The Vineyard", difficulty: "Medium", duration: "30 mins", description: "A Tuscan wine cellar with vintage codes.", theme: "Cozy", imagePrompt: "Wine cellar, oak barrels, dusty bottles, dim lighting", isPremium: true, puzzles: [{ id: "p71", question: "Wine vintage 1997 aged 25 years. Current year?", type: "code", answer: "2022", hints: ["Add years to vintage"], solution_explanation: "1997 + 25 = 2022" }] },
    { id: "room-72", title: "The Carnival", difficulty: "Easy", duration: "20 mins", description: "Creepy abandoned carnival with fortune teller's riddles.", theme: "Horror", imagePrompt: "Abandoned carnival, ferris wheel, fortune booth, peeling paint", isPremium: false, puzzles: [{ id: "p72", question: "Fortune: 'Your lucky number is prime, between 10 and 20, sum of digits is 4.' What is it?", type: "code", answer: "13", hints: ["Prime numbers 11,13,17,19", "1+3=4"], solution_explanation: "13 is prime and 1+3=4" }] },
    { id: "room-73", title: "The Blacksmith", difficulty: "Medium", duration: "30 mins", description: "A medieval forge with puzzles in steel.", theme: "Historical", imagePrompt: "Blacksmith forge, anvil, glowing metal, hammers, sparks", isPremium: true, puzzles: [{ id: "p73", question: "Forge temp: 1000°C. Cool by half. New temp?", type: "code", answer: "500", hints: ["Divide by 2"], solution_explanation: "1000 ÷ 2 = 500°C" }] },
    { id: "room-74", title: "The Aquarium", difficulty: "Easy", duration: "20 mins", description: "After hours in a grand aquarium. The fish know the way.", theme: "Coastal", imagePrompt: "Giant aquarium, sharks, coral reef, blue lighting", isPremium: false, puzzles: [{ id: "p74", question: "Tank has 50 fish. 10 are sharks. What fraction are NOT sharks?", type: "code", answer: "4/5", hints: ["40 non-sharks", "40/50 simplify"], solution_explanation: "40/50 = 4/5" }] },
    { id: "room-75", title: "The Satellite", difficulty: "Expert", duration: "50 mins", description: "Aboard a communications satellite. Adjust the orbit to survive reentry.", theme: "Space", imagePrompt: "Satellite interior, solar panels, Earth below, control systems", isPremium: true, puzzles: [{ id: "p75", question: "Orbit time: 90 mins. How many orbits in 24 hours?", type: "code", answer: "16", hints: ["24 hours = 1440 mins", "1440/90"], solution_explanation: "1440 ÷ 90 = 16 orbits" }] }
];
